### ISSUE TITLE
Publish report from local execution in JetBrains Rider

### ISSUE THREAD

**Issue by shatulsky** [reportportal/agent-net-nunit#76]
Hi.
I tried to launch both:
https://github.com/reportportal/example-net-nunit
![image](https://user-images.githubusercontent.com/22248285/125091080-c6ee5d00-e0d8-11eb-93ca-a2d12511316d.png)
and
https://github.com/reportportal/example-net-xunit
![image](https://user-images.githubusercontent.com/22248285/125091697-5136c100-e0d9-11eb-83f7-53d0f4839e8a.png)
I changed the server to the correct value that is working for me in VS.

Tests execution in Rider does not push any launches to the report portal server.

**Comment by nvborisenko** [comment]
Actually I don't have Rider installed. Would much appreciate to get diagnostical information about tests run (right click > diagnostics).

As far as I know by default Rider includes test runner for nunit/xunit. Thus Rider doesn't see plugins for test runner.

Also please try to play with Rider settings in Unit Testing section, like tell Rider to use solution/project installed test runner instead of default.

**Comment by nvborisenko** [comment]
Installed Rider, changed configuration to use custom nunit runner from my tests output folder.

![image](https://user-images.githubusercontent.com/22616990/148833233-7041df7b-bbd3-43c9-a9b9-852a9a2aac2c.png)

And I see report in RP.
